services:
  - type: web
    name: futo-emerald-http-server
    runtime: node
    rootDir: apps/http-server
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: node dist/index.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: BOSS_WALLET_KEY
        sync: false